### ISSUE TITLE
language folder name pt_pt throws exception

### ISSUE THREAD

**Issue by purusothamana** [pwa-builder/PWABuilder-CLI#274]
Hi,

I am working on a edge extension project.
I am getting exception when I execute this command.

**manifoldjs -l debug -p edgeextension package  MSGextensionName\edgeextension\manifest**

This error does not occur when perform one of the following action and execute same command.
1. delete pt_pt folder
2. rename pt_pt to any valid locale name such as pt_br or en_gb

commandline output:
=============

E:\EdgeExtnSigning\Signed>manifoldjs -l debug -p edgeextension package  MSGextensionName\edgeextension\manifest
[debug] manifoldjs  : Loading platform module: manifoldjs-edgeextension
[debug] manifoldjs  : Packaging the 'Microsoft Edge Extension Platform' app...
[info ] edgeextension: Packaging the Microsoft Edge Extension Platform app...
[debug] manifoldjs  : Unable to create the package locally. Invoking the CloudAppX service instead...
[debug] manifoldjs  : Invoking the CloudAppX service...
**[error] manifoldjs  : Failed to package the Microsoft Edge Extension Platform app.
                          at C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\manifoldjs-lib\lib\projectBuilder.js:140:29**
                          at _rejected (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:864:24)
                          at C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:890:30
                          at Promise.when (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:1142:31)
                          at Promise.promise.promiseDispatch (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:808:41)
                          at C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:624:44
                          at runSingle (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:137:13)
                          at flush (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:125:13)
                          at _combinedTickCallback (internal/process/next_tick.js:73:7)
                          at process._tickCallback (internal/process/next_tick.js:104:9)
                      Failed to create the package. The CloudAppX service returned an error - Internal Server Error (500): APPX package generation failed. Error: Command failed:
                          at Request._callback (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\manifoldjs-edgeextension\lib\appPackage.js:72:32)
                          at Request.self.callback (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\request\request.js:188:22)
                          at emitTwo (events.js:106:13)
                          at Request.emit (events.js:191:7)
                          at Request.<anonymous> (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\request\request.js:1171:10)
                          at emitOne (events.js:96:13)
                          at Request.emit (events.js:188:7)
                          at IncomingMessage.<anonymous> (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\request\request.js:1091:12)
                          at IncomingMessage.g (events.js:291:16)
                          at emitNone (events.js:91:20)
[error] manifoldjs  : One or more platforms could not be generated successfully.
                          at C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\manifoldjs-lib\lib\projectBuilder.js:28:23
                          at _fulfilled (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:854:54)
                          at self.promiseDispatch.done (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:883:30)
                          at Promise.promise.promiseDispatch (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:816:13)
                          at C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:624:44
                          at runSingle (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:137:13)
                          at flush (C:\Users\Purush\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:125:13)
                          at _combinedTickCallback (internal/process/next_tick.js:73:7)
                          at process._tickCallback (internal/process/next_tick.js:104:9)

Thanks,
Purusothaman A

**Comment by davrous** [comment]
Thanks for your report. This issue has been inactive for a long time and looks like you've found a workaround. Support for extension has been maintained on pwabuilder but please come back to us if it's a big issue for you. Thanks!
