### ISSUE TITLE
Failed to create the package. The CloudAppX service returned an error - Internal Server Error (500): APPX package generation failed

### ISSUE THREAD

**Issue by wannikid** [pwa-builder/PWABuilder-CLI#331]
Hello,

I am trying to generate the AppX pachage for my [PWA](https://stockvoodoo.pythonanywhere.com)  with the help of the pwabuilder.com site. I have downloaded the generated files and added them to my project, but the AppX creation fails with following error message. Would anybody know what the reason could be?

` Failed to create the package. The CloudAppX service returned an error - Internal Server Error (500): APPX package generation failed. Error info: /*[local-name()=\"Package\" and namespace-uri()=\"http://schemas.microsoft.com/appx/manifest/foundation/windows10\"]/*[local-name()=\"Identity\" and namespace-uri()=\"http://schemas.microsoft.com/appx/manifest/foundation/windows10\"][1]/@Version"`

**Comment by Fdebijl** [comment]
Getting the same issue here when building an Edge Extension with either manifoldjs or pwabuilder. 
I followed the [instructions on msdocs](https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/packaging/using-manifoldjs-to-package-extensions#packaging-with-manifoldjs), but no dice.

```
> pwabuilder -l debug -p edgeextension -f edgeextension -m ..\client\manifest.json
  [ Ommited for brevity ]

> pwabuilder -l debug -p edgeextension package OpenTitles\edgeextension\manifest\
[debug] manifoldjs  : Loading platform module: manifoldjs-edgeextension
[debug] manifoldjs  : Packaging the 'Microsoft Edge Extension Platform' app...
[info ] edgeextension: Packaging the Microsoft Edge Extension Platform app...
[debug] manifoldjs  : Unable to create the package locally. Invoking the CloudAppX service instead...
[debug] manifoldjs  : Invoking the CloudAppX service...
[error] manifoldjs  : Failed to package the Microsoft Edge Extension Platform app.
                          at C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\manifoldjs-lib\lib\projectBuilder.js:140:29
                          at _rejected (C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:864:24)
                          at C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:890:30
                          at Promise.when (C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:1142:31)
                          at Promise.promise.promiseDispatch (C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:808:41)
                          at C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:624:44
                          at runSingle (C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:137:13)
                          at flush (C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:125:13)
                          at process._tickCallback (internal/process/next_tick.js:61:11)
                      Failed to create the package. The CloudAppX service returned an error - Internal Server Error (500): APPX package generation failed. Package creation failed.
                          at Request._callback (C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\manifoldjs-edgeextension\lib\appPackage.js:72:32)
                          at Request.self.callback (C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\request\request.js:185:22)
                          at Request.emit (events.js:182:13)
                          at Request.<anonymous> (C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\request\request.js:1161:10)
                          at Request.emit (events.js:182:13)
                          at IncomingMessage.<anonymous> (C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\request\request.js:1083:12)
                          at Object.onceWrapper (events.js:273:13)
                          at IncomingMessage.emit (events.js:187:15)
                          at endReadableNT (_stream_readable.js:1085:12)
                          at process._tickCallback (internal/process/next_tick.js:63:19)
[error] manifoldjs  : One or more platforms could not be generated successfully.
                          at C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\manifoldjs-lib\lib\projectBuilder.js:28:23
                          at _fulfilled (C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:854:54)
                          at C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:883:30
                          at Promise.promise.promiseDispatch (C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:816:13)
                          at C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:624:44
                          at runSingle (C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:137:13)
                          at flush (C:\Users\Floris\AppData\Roaming\npm\node_modules\manifoldjs\node_modules\q\q.js:125:13)
                          at process._tickCallback (internal/process/next_tick.js:61:11)

```

Both packaged are installed globally with versions
manifoldjs@0.7.6
pwabuilder@2.0.3-rc.0

Node is version 10.9.0, running on Windows 10 v1809, build 17763.316

**Comment by lucaasrojas** [comment]
@wannikid what's the current status? Did you find a solution?

**Comment by wannikid** [comment]
I tried to run it again. This time I changed my hosting provider and also activated Win10 Dev mode, but I still get the "Package building error".
