### ISSUE TITLE
Generating IOS package fails (500 error on the site, nodeback is not a function in cli)

### ISSUE THREAD

**Issue by serebrov** [pwa-builder/PWABuilder-CLI#337]
I am trying to generate a sample package for https://app.starbucks.com.

The iOS package fails both on the pwabuilder.com (no message, 500 error in network tab with no output) and via cli:

```
pwabuilder https://app.starbucks.com -p ios -l debug 
[info ] pwabuilder  : Scanning https://app.starbucks.com for manifest...
[info ] pwabuilder  : Found a w3c manifest...
[debug] pwabuilder  : Manifest contents:
                      {
                          "short_name": "Starbucks",
                          "name": "Starbucks",
                          "icons": [
                              {
                                  "src": "/weblx/images/icons/pwa-icon-192.png",
                                  "sizes": "192x192",
                                  "type": "image/png"
                              },
                              {
                                  "src": "/weblx/images/icons/pwa-icon-512.png",
                                  "sizes": "512x512",
                                  "type": "image/png"
                              }
                          ],
                          "start_url": "https://app.starbucks.com/?utm_source=homescreen",
                          "display": "standalone",
                          "orientation": "portrait",
                          "theme_color": "#00A862",
                          "background_color": "#FFFFFF",
                          "related_applications": [
                              {
                                  "platform": "itunes",
                                  "url": "https://itunes.apple.com/us/app/starbucks/id331177714?mt=8",
                                  "id": "331177714"
                              },
                              {
                                  "platform": "play",
                                  "url": "https://play.google.com/store/apps/details?id=com.starbucks.mobilecard&hl=en",
                                  "id": "com.starbucks.mobilecard"
                              }
                          ]
                      }
[debug] pwabuilder  : Loading platform module: pwabuilder-cordova
[warn ] ios         : Manifest validation SUGGESTION - An app icon of the following sizes is required: 76x76, 120x120, 152x152 and 180x180(member: icons).
[warn ] ios         : Manifest validation SUGGESTION - An 1024x1024 app icon for the App Store is required(member: icons).
[warn ] ios         : Manifest validation SUGGESTION - A launch image of the following sizes is required: 750x1334, 1334x750, 1242x2208, 2208x1242, 640x1136, 640x960, 1536x2048, 2048x1536, 768x1024 and 1024x768(member: icons).
[debug] pwabuilder  : Creating the 'Cordova Platform' app...
[info ] cordova     : Generating the iOS Platform app(s)...
[info ] cordova     : Creating the Cordova Platform project...
[debug] pid:32592   : Launching external process: '/home/seb/.nvm/versions/node/v10.16.0/lib/node_modules/pwabuilder/node_modules/.bin/cordova create cordova com.starbucks.app Starbucks'
[debug] pid:32592   : 
[debug] pid:32592   : You have been opted out of telemetry. To change this, run: cordova telemetry on.
[debug] pid:32592   : Creating a new cordova project.
[info ] cordova     : Copying the Cordova Platform manifest to the app folder...
[info ] cordova     : Adding the following plugins to the Cordova project: cordova-plugin-hostedwebapp@0.3.x cordova-plugin-whitelist...
[debug] pid:32613   : Launching external process: '/home/seb/.nvm/versions/node/v10.16.0/lib/node_modules/pwabuilder/node_modules/.bin/cordova plugin add cordova-plugin-hostedwebapp@0.3.x cordova-plugin-whitelist'
[debug] pid:32613   : 
[debug] pid:32613   : You have been opted out of telemetry. To change this, run: cordova telemetry on.
[debug] pid:32613   : Adding cordova-plugin-hostedwebapp to package.json
[debug] pid:32613   : Saved plugin info for "cordova-plugin-hostedwebapp" to config.xml
[debug] pid:32613   : Adding cordova-plugin-whitelist to package.json
[debug] pid:32613   : Saved plugin info for "cordova-plugin-whitelist" to config.xml
[info ] cordova     : Adding the following Cordova platforms: ios...
[debug] pid:32723   : Launching external process: '/home/seb/.nvm/versions/node/v10.16.0/lib/node_modules/pwabuilder/node_modules/.bin/cordova platform add ios'
[debug] pid:32723   : 
[debug] pid:32723   : You have been opted out of telemetry. To change this, run: cordova telemetry on.
[debug] pid:32723   : Using cordova-fetch for cordova-ios@~4.5.4
[debug] pid:32723   : Adding ios project...
[debug] pid:32723   : Creating Cordova project for the iOS platform:
[debug] pid:32723   : 	Path: platforms/ios
[debug] pid:32723   : 	Package: com.starbucks.app
[debug] pid:32723   : 	Name: Starbucks
[debug] pid:32723   : iOS project created with cordova-ios@4.5.5
[debug] pid:32723   : Installing "cordova-plugin-hostedwebapp" for ios
[debug] pid:32723   : Plugin doesn't support this project's cordova-ios version. cordova-ios: 4.5.5, failed version requirement: <=4.1.9
[debug] pid:32723   : Skipping 'cordova-plugin-hostedwebapp' for ios
[debug] pid:32723   : Installing "cordova-plugin-whitelist" for ios
[debug] pid:32723   : Updating Cordova configuration from W3C manifest...
[debug] pid:32723   : The module "ConfigParser" has been factored into "cordova-common". Consider update your plugin hooks.
[debug] pid:32723   : Downloaded icon file: /home/seb/web/shortform/Shortform-ios/Starbucks/cordova/weblx/images/icons/pwa-icon-192.png
[debug] pid:32723   : Downloaded icon file: /home/seb/web/shortform/Shortform-ios/Starbucks/cordova/weblx/images/icons/pwa-icon-512.png
[debug] pid:32723   : The module "ConfigParser" has been factored into "cordova-common". Consider update your plugin hooks.
[debug] pid:32723   : Removing default images from Cordova configuration...
[debug] pid:32723   : --save flag or autosave detected
[debug] pid:32723   : Saving ios@~4.5.5 into config.xml file ...
[info ] cordova     : Processing the 'ios' Cordova platform...
[info ] cordova     : Copying documentation from '/home/seb/.nvm/versions/node/v10.16.0/lib/node_modules/pwabuilder/node_modules/pwabuilder-cordova/lib/docs/ios' to '/home/seb/web/shortform/Shortform-ios/Starbucks/cordova/platforms/ios'...
[info ] cordova     : Creating a shortcut for the 'ios' Cordova platform...
[info ] cordova     : Writing the generation information for the 'Cordova Platform' platform to '/home/seb/web/shortform/Shortform-ios/Starbucks/cordova/platforms/ios/generationInfo.json'...
[info ] cordova     : Writing the generation information for the 'Cordova Platform' platform to '/home/seb/web/shortform/Shortform-ios/Starbucks/cordova/generationInfo.json'...
/home/seb/.nvm/versions/node/v10.16.0/lib/node_modules/pwabuilder/node_modules/q/q.js:155
                throw e;
                ^

TypeError: nodeback is not a function
    at /home/seb/.nvm/versions/node/v10.16.0/lib/node_modules/pwabuilder/node_modules/q/q.js:2055:17
    at runSingle (/home/seb/.nvm/versions/node/v10.16.0/lib/node_modules/pwabuilder/node_modules/q/q.js:137:13)
    at flush (/home/seb/.nvm/versions/node/v10.16.0/lib/node_modules/pwabuilder/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Time: 0h:00m:23s                                  
```

I am using node v10.16.0.

**Comment by chetan51** [comment]
I'm seeing this as well!

**Comment by JPustkuchen** [comment]
I can also confirm this, sadly :(

**Comment by slunecniborecek** [comment]
same here, nodeback passed to nodeify (https://github.com/kriskowal/q/blame/master/q.js#L2051) is `/` in my case (which obviously is not a function). 
Using pwabuilder-edgeextension
