### ISSUE TITLE
Cannot build for Windows 10

### ISSUE THREAD

**Issue by jranma** [pwa-builder/PWABuilder-CLI#338]
Hello
Trying to build appx package for Windows10 for my PWA at https://park-oh.ch

using the web tool, I get "build error". 

Using pwabuilder CLI, I get this error: 

"[debug] pwabuilder  : Unable to create the package locally. Invoking the CloudAppX service instead...
[debug] pwabuilder  : Invoking the CloudAppX service...
[error] pwabuilder  : Failed to package the Windows 10 Platform app.
                          at /usr/lib/node_modules/pwabuilder/node_modules/pwabuilder-lib/lib/projectBuilder.js:196:31
                          at _rejected (/usr/lib/node_modules/pwabuilder/node_modules/q/q.js:864:24)
                          at /usr/lib/node_modules/pwabuilder/node_modules/q/q.js:890:30
                          at Promise.when (/usr/lib/node_modules/pwabuilder/node_modules/q/q.js:1142:31)
                          at Promise.promise.promiseDispatch (/usr/lib/node_modules/pwabuilder/node_modules/q/q.js:808:41)
                          at /usr/lib/node_modules/pwabuilder/node_modules/q/q.js:624:44
                          at runSingle (/usr/lib/node_modules/pwabuilder/node_modules/q/q.js:137:13)
                          at flush (/usr/lib/node_modules/pwabuilder/node_modules/q/q.js:125:13)
                          at process._tickCallback (internal/process/next_tick.js:61:11)
                      Failed to create the package. The CloudAppX service returned an error - Internal Server Error (500): APPX package generation failed. Error info: /*[local-name()="Package" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"]/*[local-name()="Applications" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"][1]/*[local-name()="Application" and namespace-uri()="http://schemas.microsoft.com/appx/manifest/foundation/windows10"][1]/@Id
                          at Request._callback (/usr/lib/node_modules/pwabuilder/node_modules/pwabuilder-windows10/lib/appPackage.js:74:32)
                          at Request.self.callback (/usr/lib/node_modules/pwabuilder/node_modules/request/request.js:185:22)
                          at Request.emit (events.js:198:13)
                          at Request.<anonymous> (/usr/lib/node_modules/pwabuilder/node_modules/request/request.js:1161:10)
                          at Request.emit (events.js:198:13)
                          at IncomingMessage.<anonymous> (/usr/lib/node_modules/pwabuilder/node_modules/request/request.js:1083:12)
                          at Object.onceWrapper (events.js:286:20)
                          at IncomingMessage.emit (events.js:203:15)
                          at endReadableNT (_stream_readable.js:1143:12)
                          at process._tickCallback (internal/process/next_tick.js:63:19)
[error] pwabuilder  : One or more platforms could not be generated successfully.
                          at /usr/lib/node_modules/pwabuilder/node_modules/pwabuilder-lib/lib/projectBuilder.js:29:23
                          at _fulfilled (/usr/lib/node_modules/pwabuilder/node_modules/q/q.js:854:54)
                          at /usr/lib/node_modules/pwabuilder/node_modules/q/q.js:883:30
                          at Promise.promise.promiseDispatch (/usr/lib/node_modules/pwabuilder/node_modules/q/q.js:816:13)
                          at /usr/lib/node_modules/pwabuilder/node_modules/q/q.js:624:44
                          at runSingle (/usr/lib/node_modules/pwabuilder/node_modules/q/q.js:137:13)
                          at flush (/usr/lib/node_modules/pwabuilder/node_modules/q/q.js:125:13)
                          at process._tickCallback (internal/process/next_tick.js:61:11)
"
please help :)
cheers, julien

**Comment by jranma** [comment]
On my side, the problem came from a non-standard character in the name of my application. 
check if you don't have a "-","!" because the software doesn't like them.
